# Generated by Django 3.0.6 on 2020-06-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_profile', models.CharField(max_length=500)),
                ('comp_name', models.CharField(max_length=50)),
                ('comp_partners', models.CharField(max_length=100)),
                ('comp_emp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_name', models.CharField(max_length=50)),
                ('checkout_no', models.BinaryField(max_length=20)),
                ('contact_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_no', models.BinaryField(max_length=20)),
                ('contact_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='productView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productView_name', models.CharField(max_length=50)),
                ('productView_no', models.BinaryField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_name', models.CharField(max_length=100)),
            ],
        ),
    ]
